### ISSUE TITLE
Add "Next Record" button

### ISSUE THREAD

**Issue by joshuago78** [thegetty/portal#640]
When in an item detail page, the user should be able to click a button to see the item detail page of the next item in the results list.
- [x] @kristenGRI will mock up a design
- [ ] @susanley will implement

**Comment by kristenGRI** [comment]
@joshuago78 attached a design for link placement. Added them to the top and bottom of the record similar to where you would find the pagination on the results page. Please review and let me know if you approve the design.
![rp_itemdetail_v2 2](https://cloud.githubusercontent.com/assets/15019503/19248436/e58ada54-8ee4-11e6-80e3-82c38ed06242.jpg)

**Comment by joshuago78** [comment]
This looks good. I wonder if the top links should be above the "Record Detail" header?

**Comment by kristenGRI** [comment]
@joshuago78 attaching a comp for your recommendation. It seems a little weird to have page functionality above the header but it also seems like to it could make sense to keep it a little more separated from the details of the record (and it keeps all relevant record detail sandwiched between the navigation.)

I just realized one possible concern though with this functionality in general: are we going to have a "back to results link" in addition to these? I could see it being slightly frustrating to toggle back and forth between a few a records and then have to either click the back button several times to get back to my search or having to go home and start over. 
![rp_itemdetail_v2 2b](https://cloud.githubusercontent.com/assets/15019503/19250611/1556212a-8ef0-11e6-94de-181373689e0e.jpg)

**Comment by joshuago78** [comment]
I like this better with the navigation links being outside the scope of the record details.

And yes, you are right. If we add this kind of navigation we will definitely need a back to search link as well.

**Comment by kristenGRI** [comment]
Great! Ok, mocked up two versions with a back to results link. I think having the links centered makes the most sense as far as order of operations, but I think it might also depend on if we think users might use most. In that case, the second option with the Back to results link being justified to the left might be best (as they can click that link faster and easier than if it were in the center of the next and previous.)
![rp_itemdetail_v2 3a](https://cloud.githubusercontent.com/assets/15019503/19253946/ab2f6c16-8f03-11e6-8a4a-6521c3b5acf8.jpg)
![rp_itemdetail_v2 3b](https://cloud.githubusercontent.com/assets/15019503/19253947/ab44a8ce-8f03-11e6-8c5c-f6d212f5d79f.jpg)

**Comment by joshuago78** [comment]
Let's go with the centered links

**Comment by susanley** [comment]
@joshuago78 @kristenGRI Noted.
